### ISSUE TITLE
PSA: repo was renamed

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/scroll-to-text-fragment#108]
Just letting you know that we renamed your repo to adhere to WICG guidelines as part of https://github.com/WICG/admin/issues/112

Redirects should happen automatically. Feel free to close this.

**Comment by bokand** [comment]
Got it, thank you!

**Comment by foolip** [comment]
Occurrences of "ScrollToTextFragment" will have to be replaced, and note that https://wicg.github.io/ScrollToTextFragment/ in fact doesn't redirect, so you'll want to hunt down those URLs and replace them elsewhere too.

**Comment by bokand** [comment]
> https://wicg.github.io/ScrollToTextFragment/ in fact doesn't redirect, so you'll want to hunt down those URLs and replace them elsewhere too.

It's redirecting for me, maybe it just needed some time for the change to propagate? In any case, I'll update all occurrences shortly.

**Comment by foolip** [comment]
@bokand those redirects don't get set up automatically, but @marcoscaceres fixed it in https://github.com/WICG/wicg.github.io/commit/7c373b2f6bde27928a5411271c7b789911097f8c
