### ISSUE TITLE
Integration with Google Search Featured Snippets seems a bit puzzling.

### ISSUE THREAD

**Issue by will-ca** [WICG/scroll-to-text-fragment#110]
Personally, when I see a "Featured Snippet" in Google Search results, I can usually respond within one of two categories:

1) If the snippet contains the information that I wanted, then I note that and close the tab. I never click the link since the snippet already said what I was looking for, so the highlighted text/autoscroll is never encountered and is not useful.

2) If I open the page, then that means that the text snippet did not contain the information I was looking for, and I'm more interested in the other content on the page. In this case, scrolling to and highlighting the snippet in bright colours is actively distracting and unhelpful.

Because the highlighted snippet is an exact, redundant repeat of the excerpted section displayed prominently on the prior search results page, the only situations where it will be encountered are the ones where it is explicitly not useful.

I do not know if this pattern reflects other user's behaviour, but it seems a reasonable presumption.

**Comment by bokand** [comment]
This is an issue with Google Search and not with the underlying technology being developed here. So again, personal opinion:

> If I open the page, then that means that the text snippet did not contain the information I was looking for, and I'm more interested in the other content on the page. In this case, scrolling to and highlighting the snippet in bright colours is actively distracting and unhelpful.

This depends a lot on the page - if the snippet is embedded deep in a long page, the user may want more context. Starting them off from the featured snippet that induced them to click the link in the first place seems like a better starting point than the top of the page which may not be relevant.

Additionally, the featured snippet is quite short. If the content they're looking for is longer than the snippet the user may wish simply to read more of the snipped text.

**Comment by bokand** [comment]
Issue hygiene. Given this is related to how Google Search uses this feature, I'm to close this as there isn't anything actionable here for this spec.
