### ISSUE TITLE
Special handling for multiple paragraphs?

### ISSUE THREAD

**Issue by divillysausages** [WICG/scroll-to-text-fragment#116]
Is there something special that needs to be done when it comes to creating a link with text that spans multiple paragraphs?

For example, I have the html:

````
<p>...foo bar baz.</p>
<p>The quick brown fox...</p>
````

I create the link as such:

````
var s = document.getSelection();
var str = s.toString()
encodeURIComponent(str)
````

For a final URI of `...#:~:text=foo%20bar%20baz.%0A%0AThe%20quick%20brown%20fox`

When I load it up in Chrome, it doesn't highlight the text. As far as I can tell, it's related to the `%0A` part of the encoding, but I haven't yet found a way around it

**Comment by bokand** [comment]
Paragraphs are block level so the individual terms cannot span them. The explainer could be clearer about this but the [spec has details and examples](https://wicg.github.io/scroll-to-text-fragment/#example-73638554:~:text=While%20the%20matching%20text%20and%20its%20prefix/suffix%20can%20span%20across%20block-boundaries,%20the%20individual%20parameters%20to%20these%20steps%20cannot).

In this case, you'd have to use a range match `:~:text=foo%20bar,brown%20fox` or use multiple terms `:~:text=foo%20bar%20baz&text=The%20quick%20brown%20fox`
