### ISSUE TITLE
Potential destruction of SPAs, and bad link sharing user experience

### ISSUE THREAD

**Issue by wmichelin** [WICG/scroll-to-text-fragment#118]
These links destroy previews in iMessage, and several other messaging applications. Please remove these changes and don't mess with people's links. People can easily `command + F` for what they were searching for.

**Comment by rjmunro** [comment]
That sounds like a bug in iMessage. If a browser a legacy browser can render it, an iMessage preview should be able to render it. Does iMessage break on other links with a `#`?

People cannot easily "command + F" for "what they were searching for" - not all uses are search engines, I frequently want to share a link to place not at the top of a page, and on mobile, the equivalent to "command + F" is really hard to find, then typing "what they were searching for" is difficult.

**Comment by wmichelin** [comment]
> People cannot easily "command + F" for "what they were searching for" - not all uses are search engines, I frequently want to share a link to place not at the top of a page, and on mobile, the equivalent to "command + F" is really hard to find, then typing "what they were searching for" is difficult.

This is what anchor links are for. Do we need a second solution for the same thing?

**Comment by tilgovi** [comment]
> This is what anchor links are for. Do we need a second solution for the same thing?

Anchor links depend on the publisher to provide the anchors. This specification does not. That gives power to users to navigate and share in ways that they could not before.

**Comment by bathos** [comment]
What’s meant by “destruction of SPAs” here? Are you referring to browsers that predated the history API (IE <= 9), where the fragment identifier would be used by some routing libraries as a fallback?

**Comment by wmichelin** [comment]
@bathos Yes

**Comment by wmichelin** [comment]
> Anchor links depend on the publisher to provide the anchors. This specification does not. That gives power to users to navigate and share in ways that they could not before.

@tilgovi This is a preferable solution over trying to highlight entire sections of pages in yellow, arbitrarily, with no regard to how the website content is loaded in, at what time it is loaded in, and destroying the URL detection of multiple messaging applications. 

At a bare minimum, this should be a feature that is able to be shut off by power users, as Google is starting to render their search results with these links and it's a very, very poor and jarring user experience.

**Comment by zba** [comment]
I think it would be good if UA remove this part from omnibox url after navigation, so sharing would not be affected.

**Comment by will-ca** [comment]
> > This is what anchor links are for. Do we need a second solution for the same thing?
> 
> Anchor links depend on the publisher to provide the anchors. This specification does not. **That gives power to users to navigate and share in ways that they could not before.**

(Emphasis mine.)

I'm curious:

Do you expect that the average user will be able and willing to manually construct and test a spec-compliant URL every time they have a link to a specific passage that they want to share?

Or is the expectation that browsers will add a very specific and only conditionally visible context-menu button that generates a valid URL fragment, and users will instead find and use that?

**So far, I've only ever seen this feature take power** ***away*** **from both users** ***and*** **authors, by giving linking websites the ability to unilaterally and sneakily editorialize their content.**

And whether that's deliberate or not, I don't think we should just ignore the fact that this spec has come from the single biggest and most powerful linking website on the planet.

And frankly? **Given that we're presently living in a civilization which already is seeing major democratic backsliding and civil disturbances in multiple countries as a direct result of how easy it is decontextualize snippets of information that other people have published online? Creating a tool which makes it even easier to cherry-pick and promote specific passages— right on other people's pages, transparently, without asking or even informing either the user or the website in question— doesn't just contribute to a poor user experience, but smells of irresponsibility, callousness, and myopia.**

**Comment by will-ca** [comment]
> That sounds like a bug in iMessage. If a legacy browser can render it, an iMessage preview should be able to render it. Does iMessage break on other links with a `#`?

When a new proposed feature breaks an existing and established application by changing the behaviour and use of something which has already existed and been universally accepted for years, the takeaway is that it "sounds like a bug" in the existing, standards-compliant application?

**Comment by tilgovi** [comment]
> Is it expected that the average user will be able and willing to manually construct and test a spec-compliant URL every time they have a specific passage on a website that they want to share?

I don't think that's expected for ordinary fragments. Fragment identifiers aren't typically visible, except when we expose them as anchors for copying and pasting as URLs.

> Or is the expectation that browsers will add a very specific and only conditionally visible context-menu button that generates a valid URL fragment, and users will instead find and use that?

I would expect everyone—browsers, publishers, platforms, users—to figure this out by experimentation, much as a lot of the Web has come to be the way it is. The specification shouldn't have normative language for this.

> So far, I've only ever seen this feature take power away from both users and authors, by giving linking websites the ability to unilaterally and sneakily editorialize their content.

Google has a lot of power to put a new capability into practice quickly through the close working relationship between specification authors, browser engineers, and search product engineers. As best I can tell, this objection is about how Google search as a product uses this feature, and not about the specification. I would not agree that there's anything inherently "sneaky" about quoting from or linking to something. If Chrome has this capability then _you have it, too_.  Please use it for whatever ends you consider good.

> And whether that's deliberate or not, I don't think we should just ignore the fact that this spec has come from the single biggest and most powerful linking website on the planet.

I agree that we should not. There's a long history of attempts to do similar things by others who did not have the same power. Desire for similar capability is older than the Web itself, and we should continue to ask ourselves why it's taken until now to get it.

I share your concerns, but quoting out of context does not require this specification. Quoting _with a link to the quote in context_ does. I believe there is value in being able to provide context through linking, exactly in order to push back against the forces of decontextualization you're identifying. Every time someone shares a screenshot of text when they might have shared a link to it decontextualization is happening because the Web has failed to give them the power to do otherwise. That's what I'm here to fix.

**Comment by will-ca** [comment]
@tilgovi 

> As best I can tell, this objection is about how Google search as a product uses this feature, and not about the specification. I would not agree that there's anything inherently "sneaky" about quoting from or linking to something.

Personally, I feel the "sneaky" factor comes from the fact that it's not immediately obvious whether the highlight imposed as a result of the text fragment is part of the original webpage or not.

While that is also an implementation/UI specific, I feel like the implementation is necessarily at least partly a result of what the specification says (or doesn't say).

> I share your concerns, but quoting out of context does not require this specification. Quoting *with a link to the quote in context* does. I believe there is value in being able to provide context through linking, exactly in order to push back against the forces of decontextualization you're identifying. Every time someone shares a screenshot of text when they might have shared a link to it, decontextualization is happening because the Web has failed to give them the power to do otherwise. That's what I'm here to fix.

True. I suppose it could go either of two ways.

Thank you for your time. I apologize if I came across more confrontationally or accusatorily than I should have, and I hope it works out well.

**Comment by tilgovi** [comment]
> Thank you for your time. I apologize if I came across more confrontationally or accusatorily than I should have, and I hope it works out well.

Likewise. UX concerns are important. Any ways the spec might encourage bad UX should be called out. Similarly, any way the text can be improved by adding suggestions that encourage good UX should be suggested. I hope it's clear that I share some of your concerns, but maybe we can leave those for another venue going forward and see what we can do to improve the spec, assuming there's something at its core that we can agree is worthwhile.

**Comment by bokand** [comment]
> Personally, I feel the "sneaky" factor comes from the fact that it's not immediately obvious whether the highlight imposed as a result of the text fragment is part of the original webpage or not.

FWIW, I think Chrome's implementation could do a better job of this. In M85 the highlight disappears on scroll so hopefully makes it a bit more obvious it's not part of the page. I've also considered a smooth fade-out after a second or so, though it's a bit trickier implementation-wise.

IMHO, adding these concerns into the spec would be valuable - I'll add some text to encourage implementors to take steps to differentiate the indication/highlight from page content.

**Comment by bokand** [comment]
The latter part of this issue got a little off topic but to the point:

SPAs are unaffected; the [directive](https://wicg.github.io/scroll-to-text-fragment/#the-fragment-directive) is removed from the document's URL prior to script on a page running, meaning it doesn't affect pages that use the fragment for routing.

As far as this breaking previews in other apps - I believe that's a bug in the app. This spec utilizes only [valid characters](https://url.spec.whatwg.org/#fragment-percent-encode-set) for a URL fragment so an app that breaks on this has a URL parsing issue (one that would exist with other, valid fragments).

I'm going to close this as there's no action item here - but feel free to reply if I missed something.
