### ISSUE TITLE
Escaping / Quoting for Whitespace and Commas

### ISSUE THREAD

**Issue by cryptoquick** [WICG/scroll-to-text-fragment#127]
Is there a way to escape or quote text so that Markdown and other text parsers can render links properly?

For example:

[scroll-to-text-fragment - Opting out](https://github.com/WICG/scroll-to-text-fragment#:~:text=Opting out)

[scroll-to-text-fragment - Opting out](https://github.com/WICG/scroll-to-text-fragment#:~:text="Opting out")

[scroll-to-text-fragment - Opting out](https://github.com/WICG/scroll-to-text-fragment#:~:text="Opting\ "out)

Unfortunately, only this approach actually works with Markdown, but the above would at least it would make sense:

`[scroll-to-text-fragment - Opting out](https://github.com/WICG/scroll-to-text-fragment#:~:text=Opting\&nbsp;out)`

Example of the above in GHMD:

[scroll-to-text-fragment - Opting out](https://github.com/WICG/scroll-to-text-fragment#:~:text=Opting\&nbsp;out)

That does not work in browsers, unfortunately.

Additionally, `\n` or `\r\n` should be considered to highlight across multiple lines. One can already accomplish this with comma syntax, but that approach wouldn't allow for exclusion of matches that are in-line.

With escaping or quoting, one could also exclude commas from being parsed as prefixes or suffixes.

I couldn't figure out if the spec mentioned all this, but if so, feel free to point it out. :)

**Comment by bokand** [comment]
A space is technically invalid in a URL. The text fragment is expected to be in percent-encoded format - browsers like Chrome will automatically do this from the address bar so it's acepted but technically you'd have to write `Opting%20out`.

e.g. link that works in markdown `[scroll-to-text-fragment - Opting out](https://github.com/WICG/scroll-to-text-fragment#:~:text=Opting%20out)` causes [scroll-to-text-fragment - Opting out](https://github.com/WICG/scroll-to-text-fragment#:~:text=Opting%20out)

Re: new lines, CSS/HTML has specific rules about collapsing whitespace that's part of a node's data (it's on my backlog to specify this better in the spec, #98 ) so literal newline characters in the data aren't presented and are removed as far as text search is concerned.

Newlines that occur as a result of block elements or `<br>` are presentational; I think that trying to capture that using escaping would be difficult in all cases. As you note, range matches ("comma syntax") covers this use case but I don't understand your point about excluding in-line matches, could you elaborate on that?

**Comment by bokand** [comment]
Doing issue hygiene and this doesn't appear to have any action to take. Going to close this but feel free to reply if there's something I missed.
