### ISSUE TITLE
Expose text-fragment to page

### ISSUE THREAD

**Issue by bokand** [WICG/scroll-to-text-fragment#128]
For compatibility reasons, we strip the fragment directive from the URL before page script has a chance to run. Even if it was available to the page, it would be difficult for the page to know in all cases which piece of text the fragment matches, if any, since it would require effectively re-implementing the browser's implementation and running it on the page.

As mentioned in [Mozilla's position](https://github.com/mozilla/standards-positions/issues/194#issuecomment-568581041-permalink:~:text=The%20marginalia%20use%20case%20described%20at%20https%3A%2F%2Findieweb.org%2Fmarginalia%20is%20not%20supported%20as%20well%20as%20it%20could%20be%2C%20since%20the%20fragment%20specifier%20is%20stripped%20from%20the%20URL.%20That%20significantly%20limits%20the%20ability%20of%20sites%20to%20show%20appropriate%20marginalia%20UX%20when%20the%20user%20loads%20a%20link%20to%20a%20specific%20text%20fragment.%20It%20could%20probably%20be%20addressed%20by%20exposing%20the%20fragment%20specifier%20via%20the%20FragmentDirective%2C%20modulo%20whatever%20the%20security%20considerations%20are%20with%20exposing%20this%20information%20to%20the%20page.%20As%20far%20as%20we%20can%20tell%2C%20those%20security%20considerations%20seem%20to%20be%20entirely%20driven%20by%20the%20search%20engine%20use%20case%2C%20and%20impose%20unnecessary%20constraints%20on%20the%20other%20use%20cases.%20That%20said%2C%20exposing%20the%20fragment%20specifier%20could%20be%20added%20in%20a%20V2%20of%20the%20API%3B%20perhaps%20along%20with%20allowing%20URLs%20to%20opt%20out%20of%20having%20it%20exposed.%20That%20would%20need%20to%20be,planned%20for%20in%20V1%20syntax%2C%20possibly.,-The) of this feature, there exist interesting use cases for knowing the text fragment, such as [marginalia](https://indieweb.org/marginalia). We should expose this information so authors can make use of it for such cases.

We have a `window.location.fragmentDirective` object used for feature detection (may move to `document` soon, see https://crbug.com/1057795). This would probably be a good place to add this information. I don't have any concrete API shape in mind yet; as a starting point, how about:

```
location.fragmentDirective ::= [ Directive* ]

Directive ::= {
  name: 'text',
  data: 'foo-,quote,-bar'
  range: Range
}
```

Where `fragmentDirective` is an array of Directive objects (text or otherwise). Each Directive would contain the type (assuming [others](https://github.com/slightlyoff/history_api#ui-state-fragments) may be added in the future), raw text data, and type-specific data. In our case, a [Range](https://dom.spec.whatwg.org/#range) object pointing to the located text, or null if it wasn't found.

Curious if anyone else has thoughts on how this should look. At a start, we should remove parts of the spec and explainer that forbid UAs from exposing this information.

**Comment by eligrey** [comment]
Something like `location.fragmentDirectives` structured as `URLSearchParams`, perhaps with a corresponding `URLFragmentDirectives` constructor which can also take full hashes as input would be ideal imo.

Currently if you want to interoperate with fragment directives, you'll need all of these helpers for cross-browser support:

```ts
// Get full 'navigation' URL including fragment directives
const getNavigationURL = () =>
  performance
    .getEntries()
    .find(({ entryType }) => 
      entryType === 'navigation'
    )?.name
  || location.href;

// Get URL fragment directives as URLSearchParams
const getFragmentDirectives = (url = getNavigationURL()) => {
  const fragment = url.indexOf('#');
  const directives = fragment !== -1 ? url.slice(fragment).indexOf(':~:') : -1;
  return new URLSearchParams(
    directives !== -1 ? url.slice(fragment + directives + 3) : '',
  );
};

// Check if browser hides fragment directives from navigated URLs
const doesBrowserHideFragmentDirectives = () => {
  const frame =
    document.createElementNS('http://www.w3.org/1999/xhtml', 'iframe');
  // prevent reflow from insertion
  frame.style.display = 'none';
  frame.width = frame.height = '1';
  // test URL that supports most Content-Security-Policy configs
  frame.src = 'about:blank#:~:';
  document.documentElement.append(frame);
  const isHidden = !frame.contentWindow.location.hash;
  frame.remove();
  return isHidden;
};

// Clear fragment directives from current page location
const clearLocalFragmentDirectives = () => {
  // location.hash = '' does not clear directives when they are hidden
  if (doesBrowserHideFragmentDirectives()) {
    history.replaceState(null, null, '');
  } else {
    location.hash = '';
  }
};
```

**Comment by eligrey** [comment]
Also nit: the current `location.fragmentDirective` stub is a misnomer. These should be directive**s** (plural) even though scroll-to-text is currently the only directive natively supported by browsers.

**Comment by tomayac** [comment]
> Also nit: the current `location.fragmentDirective` stub is a misnomer. These should be directive**s** (plural) imo even though scroll-to-text is currently the only directive natively supported by browsers.

+1. And multiple fragments are supported today: [http://example.com/#:~:text=for&text=asking-,for](http://example.com/#:~:text=for&text=asking-,for).

**Comment by flackr** [comment]
Do developers need some way to be notified when the fragment changes? e.g. similar to the hashchange event.

**Comment by eligrey** [comment]
@bokand Thanks for pointing that out! I've updated my getFragmentDirectives code snippet to account for this.

**Comment by tilgovi** [comment]
There is something nice about the highlight mechanism being unobservable, even if scrolling is not. I worry that making the directive observable undermines an interesting privacy benefit of stripping the fragment directive from the URL, which is that the fragment directive stays known only to the user and the user agent, but not the page.

I don't know how beneficial it is to hide the fragment directive from the page. For example, I don't think users would expect that the page doesn't know the fragment directive, if they think about it at all. Nevertheless, I wanted to record the implication.

**Comment by zcorpan** [comment]
As mentioned in https://github.com/WICG/scroll-to-text-fragment/issues/223#issuecomment-1489075160 and https://github.com/mozilla/standards-positions/issues/194#issuecomment-566671352 exposing the fragment directive from to page would roughly expose search terms which is not great for privacy.

The common ancestor will also match `:target` (exposed to JS via `document.querySelector()`), but maybe the fidelity of that is similar to that of checking the scrolling position?

**Comment by eligrey** [comment]
I proposed a fragment directives access spec that attempts to address the privacy concerns with sensitive directives: [https://github.com/eligrey/fragment-directives](https://github.com/eligrey/fragment-directives#readme)

**Comment by bokand** [comment]
I'm going to close this since it didn't make it into the initial incubation and I'm now trying to close out this repo in favor of moving the spec into HTML. I think further enhancements and proposals would be more productively debated in the HTML standard.
