### ISSUE TITLE
Move location.fragmentDirective to document.fragmentDirective

### ISSUE THREAD

**Issue by bokand** [WICG/scroll-to-text-fragment#130]
See https://crbug.com/1057795 and https://github.com/whatwg/html/issues/5523

Basically, `window.location` is special in all kinds of ways and is [spec'd](https://html.spec.whatwg.org/multipage/history.html#the-location-interface:location-11) to represent the URL of its document's browsing context's active document, not the Document itself. If we start adding things to `fragmentDirective` this would allow cross-origin access to values which is bad.

Moving `fragmentDirective` to live on `document` seems like a more safe and natural place for it.

**Comment by tomayac** [comment]
FYI, updated the article accordingly: https://github.com/GoogleChrome/web.dev/pull/3661.
