### ISSUE TITLE
Many ways users might not see the yellow

### ISSUE THREAD

**Issue by jidanni** [WICG/scroll-to-text-fragment#145]
Visit https://chromestatus.com/feature/4733392803332096
Click the Cat link. See the Yellow. All is working as expected.

Now scroll up or down until the yellow is off the screen.

Now place the cursor in the URL bar and hit RET.

OK for chromium, we always return to where we were browsing (no matter
what fancy fragment the URL contains. WAI probably. Fine.)

Trying the same experiment with e.g., just
https://en.wikipedia.org/wiki/Cat#Fighting in Firefox however, always
returns to the fragment location, no matter where we scrolled the page.

Conclusions: users will probably see the yellow at least the first time
we share a link with them. Maybe...
https://bugs.chromium.org/p/chromium/issues/detail?id=1127860#c10

**Comment by jidanni** [comment]
Also on Android, the [slightest budge](https://bugs.chromium.org/p/chromium/issues/detail?id=1127860#c8) makes the yellow disappear. OK these are all implementation problems. But does the standard say the yellow should stay around even if the page is budged, etc.?

**Comment by bokand** [comment]
Thanks for the report. I think this is a decision best left up to the UA so the bugs.chromium.com bug you filed is probably the best place to discuss. I've triaged it so closing this in favour of that.
