### ISSUE TITLE
Doesn't work on Chrome86

### ISSUE THREAD

**Issue by dnknn** [WICG/scroll-to-text-fragment#151]
For example:
`chrome://extensions/shortcuts#:~:text=Tampermonkey`
If the extension is installed, this `#:~:text=` will take you directly to the destination and highlight it, right? 
But when comes to Chrome86+, it is invalid, doesn't working.

- valid
![valid](https://user-images.githubusercontent.com/10995302/98688012-5c4c1c80-23a5-11eb-87f1-473f78ad733b.gif)

- invalid
![invalid](https://user-images.githubusercontent.com/10995302/98688440-cd8bcf80-23a5-11eb-8b57-13afc603cafa.gif)

**Comment by bokand** [comment]
Looks like this is only on the extensions page. Could you please file a bug at crbug.com/new?

**Comment by dnknn** [comment]
> Could you please file a bug at [crbug.com/new?](http://crbug.com/new?)
Done 
https://bugs.chromium.org/p/chromium/issues/detail?id=1147453
