### ISSUE TITLE
404 error when visiting the Github Pages version of this repository

### ISSUE THREAD

**Issue by wil93** [WICG/scroll-to-text-fragment#169]
When visiting the "Draft Spec" link, linked from this repository's README file, I get a 404 error:

https://wicg.github.io/scroll-to-text-fragment/

This link is also referenced by a number of articles on the web, like [this one](https://blog.logrocket.com/the-latest-features-of-css-in-2021/) where the link is now broken

**Comment by sideshowbarker** [comment]
This should be fixed now. If not, lemme know and we can reopen this
