### ISSUE TITLE
Consider renaming textFragmentToken

### ISSUE THREAD

**Issue by annevk** [WICG/scroll-to-text-fragment#178]
Token typically does not mean a boolean in the web platform. At least in my experience. "Capability" might be more appropriate.

**Comment by bokand** [comment]
I don't feel strongly about "token" so renaming it to be more inline with the rest of the platform and maybe more descriptive sgtm.

How about simply `allowTextFragment`? Or more accurately (since we can still safely highlight when this is false), `allowTextFragmentScrolling`?

**Comment by annevk** [comment]
Thanks, either of those works for me as well.

**Comment by annevk** [comment]
I missed the PR, but this might need a couple further tweaks. But that can also happen as part of integrating this into Fetch/HTML. We try to stay away from "flag" these days and most Fetch/HTML concepts have names that are space-separated rather than camel cased.

**Comment by bokand** [comment]
Thanks - I'm trying to get the spec into shape for upstreaming here first so I'll put up a PR to fix it later today. If you don't mind I'll add you as a reviewer.

**Comment by annevk** [comment]
Sounds good, I can probably tackle that tomorrow. (After that it'll be Jan 2.)

**Comment by bokand** [comment]
Re-opening this to make sure you can take another look post-holidays.

**Comment by annevk** [comment]
Thanks, I think this looks good.
