### ISSUE TITLE
Sec-Fetch-Site header inspection is wrong

### ISSUE THREAD

**Issue by annevk** [WICG/scroll-to-text-fragment#179]
You cannot inspect the `Sec-Fetch-Site` header as it's only appended just before the request hits the network. You cannot observe it from the code that deals with navigation.

**Comment by bokand** [comment]
If I'm reading it right, headers are appended in [HTTP-network-or-cache fetch](https://fetch.spec.whatwg.org/#http-network-or-cache-fetch). It looks like that happens on `httpRequest`, a clone of the `request` so the `request`, which is what's given to the new Document as `navigationParams` won't include headers. Do I have that right?

If so, I'll have to find another way to get or propagate that information along to/frame the new document.

**Comment by annevk** [comment]
That's right. Abstracting it somehow might make sense.
