### ISSUE TITLE
Need to specify setting start offset to zero

### ISSUE THREAD

**Issue by megangardner** [WICG/scroll-to-text-fragment#188]
in the description of the "To find a string in range" subroutine, we have these two parallel steps:

If curNode is part of a non-searchable subtree:
If curNode is not a visible text node:

In the first it is not explicitly stated that the start offset needs to be set to zero. It does explicitly say that in the second step. It should say that start offset needs to be set to zero in both steps.

**Comment by bokand** [comment]
Yup, thanks for catching it. Will fix.
