### ISSUE TITLE
Need additional continue in advancing to next non-whitespace position

### ISSUE THREAD

**Issue by megangardner** [WICG/scroll-to-text-fragment#189]
After implementing the subroutine as described here:
https://wicg.github.io/scroll-to-text-fragment/#next-non-whitespace-position

I had issues when I was starting this subroutine at the end of a node, like when parsing this URL:
https://blog.chromium.org/2019/12/chrome-80-content-indexing-es-modules.html#:~:text=the-,text,-parameter

Therefore, I added a step before 1.3. that was molded after 1.3 and 1.4 which was
 - If offset is equal to node length, do the same steps 1.4.1 and 1.4.2
 
 I believe this is necessary to have the correct functionality when starting at the end of a node.

**Comment by bokand** [comment]
Ah, yeah, I think you're right - thanks! I'll put up a fix shortly.
