### ISSUE TITLE
What characters explicitly are percent-encoded?

### ISSUE THREAD

**Issue by zamicol** [WICG/scroll-to-text-fragment#194]
I wanted to clarify, what characters are exactly percent encoded for text fragments?  The [README  suggests](https://github.com/WICG/scroll-to-text-fragment/blob/930e007bf853e6a4e6b82e8e501bb2ab0e24a67a/README.md#:~:text=dash%20(-)%2C%20ampersand%20(%26)%2C%20and%20comma%20(%2C)%20characters%20in%20text%20snippets%20must%20be%20percent-encoded) that only dash (-), ampersand (&), and comma (,) are escaped.  Then the [link]( https://url.spec.whatwg.org/#fragment-percent-encode-set ) in the [README](https://github.com/WICG/scroll-to-text-fragment/blob/930e007bf853e6a4e6b82e8e501bb2ab0e24a67a/README.md#:~:text=characters%20in%20the%20fragment%20percent%20encode%20set%20must%20be%20percent%20encoded.) references a different set of characters: SPACE,  ("),  (<), (>), and (`)

Both sets, even when added, excludes common percent encoding characters from fragment percent encoding.  

The standard percent-encoding character set would be a great option here.  

     ':', '/', '?', '#', '[', ']', '@', '!', '$', '&', "'", '(', ')', '*', '+', ',', ';', '=', as well as '%' itself. 

https://developer.mozilla.org/en-US/docs/Glossary/percent-encoding

**Comment by bokand** [comment]
The README was written long ago and doesn't go into a great level of detail. I think this is explicit in the [spec](https://wicg.github.io/scroll-to-text-fragment/#textdirectiveexplicitchar): The set of [URL code points](https://url.spec.whatwg.org/#url-code-points), less `&`, `-`, `,`, can be used without percent encoding. All other code points must be percent encoded.

**Comment by zamicol** [comment]
Thank you, give me a bit and I'll update the README with a pull request.

**Comment by zamicol** [comment]
I think this is a simple adjustment.  

[Instead of saying this](https://github.com/WICG/scroll-to-text-fragment/blob/930e007bf853e6a4e6b82e8e501bb2ab0e24a67a/README.md#:~:text=the%20text%20keyword%20will%20be):


`The text keyword will be used to identify a block of text that should be indicated. The provided text is percent-decoded before matching. Dash (-), ampersand (&), and comma (,) characters in text snippets must be percent-encoded to avoid being interpreted as part of the text fragment syntax.
`


It could read:


`The text keyword will be used to identify a block of text that should be indicated. The provided text must be percent encoded using the standard [percent encode set](https://url.spec.whatwg.org/#percent-encoded-bytes) and is then percent-decoded before matching.  The percent encode set is inclusive of dash (-), ampersand (&), and comma (,) as to avoid being interpreted as part of the text fragment syntax.
`





Also, a note of this rule should be included regarding [fragment directive itself](https://github.com/WICG/scroll-to-text-fragment/blob/930e007bf853e6a4e6b82e8e501bb2ab0e24a67a/README.md#multiple-text-directives), :




`
Users can specify multiple snippets by providing additional text directives in the fragment directive, separated by the ampersand (&) character. **Fragment directives must be percent encoded.  **
`


---

The statement that was throwing me off is informational and is simply stating that a fragment must be minimally fragment percent encode, which is obvious/expected.  I would perhaps update that as well to make it more obvious that the paragraph is informational and then compare the two:  

`
The [URL standard](https://url.spec.whatwg.org/) specifies that a fragment can contain [URL code points](https://url.spec.whatwg.org/#url-code-points), as well as [UTF-8 percent encoded characters](https://url.spec.whatwg.org/#utf-8-percent-encode). Characters in the [fragment percent encode set](https://url.spec.whatwg.org/#fragment-percent-encode-set) must be percent encoded.
**Fragment directive requires the more restrictive [percent encode set](https://url.spec.whatwg.org/#percent-encoded-bytes). **
`

**Comment by zamicol** [comment]
"Fixed" by #194.
