### ISSUE TITLE
Define "strip the fragment directive" generically, without the extra Document steps

### ISSUE THREAD

**Issue by tabatkins** [WICG/scroll-to-text-fragment#198]
I'm defining how [fragment-only CSS urls (like `url(#foo)`) work](https://w3c.github.io/csswg-drafts/css-values-4/#local-urls), and need to get the fragment so I can search for a matching ID in the tree. If the url is `#foo:~:text=foo`, presumably I want to strip the directive and just search for "foo" as the ID, but the spec doesn't currently define a generic algorithm allowing me to do this; it bundles this behavior into also updating some Document state.

Could I get that algo abstracted out, so it takes a raw fragment string and returns a pair of (fragment, directive) strings?

**Comment by bokand** [comment]
Yeah, that makes sense. I'm going to be upstreaming the spec as part of #195 so I'll make sure I do that as part of that work. I'm hoping to work on that this month.
