### ISSUE TITLE
Is fragment directive a concept, a member, or both?

### ISSUE THREAD

**Issue by annevk** [WICG/scroll-to-text-fragment#211]
Per its definition it belongs to document, but when you read something like

> The text fragment directive is one such [fragment directive](https://wicg.github.io/scroll-to-text-fragment/#fragment-directive)

it seems that it should probably be its own concept as well. And document's member holds that concept?

**Comment by bokand** [comment]
I think so? Is "concept" a formally defined term or do you just mean that we need a definition outside of a member definition?

**Comment by annevk** [comment]
That's what I mean, yes. (Concept has no formal definition.)
