### ISSUE TITLE
In mobile chrome copy link is not working with pagination (skips slug "/page/%#%")

### ISSUE THREAD

**Issue by Jonnas123** [WICG/scroll-to-text-fragment#215]
Hi, I have posts split by pagination in a page. If I am at page 2, for example, `https://mysite/book/page/2`. I highlight text , copy the fragment link and paste in address bar, but it shows like this `https://mysite/book/#:~:text={text}` but it should be `https://mysite/book/page/2/#:~:text={text}`. As you can see, it skips slug "page/2"

To reproduce the issue, please install WordPress, create 10 posts, and then add this code https://gist.github.com/mihdan/b4a218961bc609b0246ad2aa9ba0c232 to a custom template to display posts with pagination. Then try with your mobile chrome.

Please note this happens only with mobile , in desktop it works fine.

**Comment by Jonnas123** [comment]
The site is under construction. But if you don't mind, give me your email address. I can send you a credential to login.

**Comment by bokand** [comment]
Please send to bokan@chromium.org, thanks

**Comment by Jonnas123** [comment]
Sent, please check. Thank you.

**Comment by Jonnas123** [comment]
That's automatically added by this plugin Yoast. But actually the problem exists before this tag is added. And I've deactivated the plugin, the tag is removed, but nothing changes.

Actually I work with this site and I notice it's used to work before (with Chrome and Android in older version, as I remember). All the slug was copied correctly both in mobile and desktop.  Now It's just not working.

**Comment by bokand** [comment]
Hmm, are you sure you're not hitting a cached version of the page? If you can you update the URL you gave me I can take another look but it was quite clearly hitting the `<link>` case before.

**Comment by Jonnas123** [comment]
Sorry, I double check again, the tag still exists in the header. Now I use this code `remove_action('wp_head', 'rel_canonical');` to remove it from WordPress. And it works! Thanks.
