### ISSUE TITLE
The spec should be more explicit about how text directives interact with history

### ISSUE THREAD

**Issue by bokand** [WICG/scroll-to-text-fragment#217]
Currently, history entries do include the fragment directive portion of a fragment, the [stripping algorithm](https://wicg.github.io/scroll-to-text-fragment/#example-c1edb88d:~:text=Amend%20the%20traverse%20the%20history%20steps%20to%20process%20the%20fragment%20directive) is applied only when the Document is made active. The history entry's URL remains unstripped. This means back/forward navigation includes navigations to a changed fragment directive (e.g. navigating between highlights within a single document).

This seemed like the right behavior at the time but it's worth discussing the edge cases. We should also be more explicit about this in spec-text, at least with examples. Some things to consider:

- Should a highlight be part of the history just like an id-fragment (Safari's behavior here is a bit confusing to me)?
- Chrome allows "removing" a highlight via right click, how should that affect the history entry?
- What should happen on a reload?
- How should [pushState](https://wicg.github.io/scroll-to-text-fragment/#example-c1edb88d) work?

**Comment by annevk** [comment]
cc @jakearchibald @domenic

**Comment by jakearchibald** [comment]
@bokand 

> This means back/forward navigation includes navigations to a changed fragment directive (e.g. navigating between highlights within a single document).

That doesn't seem to be how implementations work. I'm not familiar with this feature, so I don't know if I'm seeing browser bugs or intended behaviour.

Test case:

https://output.jsbin.com/sejerip/2/quiet

1. Click "hello highlight"
    - Chrome: Hello highlights, hashchange, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: Hello highlights with animation, hashchange, `https://output.jsbin.com/sejerip/2/quiet#` (note URL difference)
1. Click "world highlight"
    - Chrome: World highlights, hello still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: World highlights with animation, hello still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet#`
1. Traverse back
    - Chrome: Both still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: World highlight animation replays, hello still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet#`
1. Click "#foo"
    - Chrome: Both still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet#foo`
    - Safari: Both still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet#foo`
1. Traverse back
    - Chrome: Both still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: Both still highlighted (no animations replay), hashchange, `https://output.jsbin.com/sejerip/2/quiet#`
1. Reload
    - Chrome: Nothing highlighted, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: Nothing highlighted, `https://output.jsbin.com/sejerip/2/quiet` (note the URL change)

Another test:

1. Click "hello highlight"
    - Chrome: Hello highlights, hashchange, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: Hello highlights with animation, hashchange, `https://output.jsbin.com/sejerip/2/quiet#` (note URL difference)
1. Click "world highlight"
    - Chrome: World highlights, hello still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: World highlights with animation, hello still highlighted, hashchange, `https://output.jsbin.com/sejerip/2/quiet#`
1. Reload
    - Chrome: Nothing highlighted, `https://output.jsbin.com/sejerip/2/quiet`
    - Safari: World highlighted, `https://output.jsbin.com/sejerip/2/quiet`

Soooo there's a lot of inconsistency and bugs here.

---

Firstly, I don't think `hashchange` should fire if the fragment hasn't changed in terms of what `location` sees ([spec](https://html.spec.whatwg.org/multipage/browsing-the-web.html#updating-the-document:event-hashchange)).

In terms of the rest, there are three places we could put the data, and each behaves differently:

- Document
- Document state
- History entry

I don't think we should store the state in the URL, although this would be equivalent to "history entry", just more hacky.

## Document

- Traversal doesn't change the highlight
- Reload loses the highlight
- Highlights could be additive (like Chrome/Safari) or replacing

This seems to match Chrome's current behaviour. Although, I question why these navigations create new history entries when there's no difference between the two history entries.

## Document state

- Traversal doesn't change the highlight
- Reload retains the highlight state
- Highlights could be additive (like Chrome/Safari) or replacing

Again, I'd question why these navigations create new history entries when there's no difference between the two history entries.

## History entry

- Traversal changes the highlight
- Reload retains the highlight state
- Highlights could be additive (like Chrome/Safari) or replacing. With additive, each history entry would contain a copy of everything to highlight.

When navigating to "#foo" in either a push/replace, it could copy the highlight state from the previous/to-replace entry. I think that's similar to how the navigation API passes its state around.

---

Which to go with depends on the desired behaviour.

**Comment by bokand** [comment]
Thanks Jake for the thorough analysis! This is an area where I didn't think through the model in the detail I should have - better late than never though...

One thing that I think is missing in your demo is scroll. Chrome's behavior (bug?) is that it doesn't remove highlights when moving to a different text directive but it does scroll, if you move your "hello" and "world" `<p>`s to require scrolling, navigating back/forward will indeed scroll between them (though, I'd have to confirm in Chrome's case whether that's happening due to scroll state being restored or if we are actually re-processing the directive).

I've run out of time today but I'll give these cases a deeper think tomorrow.

**Comment by jakearchibald** [comment]
Ugh, I realised the scroll thing and intended to edit my comment. I guess I forgot. Yeah, it's just restoring scroll position rather than scrolling to the highlight. I think that's reasonable behaviour, but I'm still kinda surprised the highlight persists when going back.

**Comment by annevk** [comment]
I think the highlight makes sense. It's the same as if you went back to a fragment navigation and the page uses `:target`.

**Comment by jakearchibald** [comment]
Hmm, are you sure?

https://output.jsbin.com/sejerip/2/quiet - if you click "hello highlight" then "world highlight" you end up with both highlighted. If you then click "#foo", both are still highlighted. That isn't how `:target` works.

I'd prefer a model more like `:target` for consistency, but I assume there's some reason both implementations went for additive highlighting?

**Comment by annevk** [comment]
Oh. Hah! I'm not sure there's a good reason for the existing behavior. I agree with you.

**Comment by bokand** [comment]
> https://output.jsbin.com/sejerip/2/quiet - if you click "hello highlight" then "world highlight" you end up with both highlighted. If you then click "#foo", both are still highlighted. That isn't how :target works.

The behavior differs if I change the text directive directly from the address bar - in that case the first highlight gets removed. Navigating through history it seems like each highlight gets 2-3 entries...and then the highlights are additive.

In Chrome's case, I believe the additive behavior wasn't intentional - I suspect the same for Safari.

> Would it make sense to continue stripping it from the URL's fragment, but store the state in the session history entry, similar to scroll restoration mode?

sgtm, I'll try this approach, to summarize:

- Store the fragment directive separately on a HistoryEntry, strip it from the entry's URL
- Process the fragment directive when traversing history but don't cause scroll to the highlight. Scroll position will come from the saved scroll state (or avoided if scroll restoration is manual) - this matches regular fragment navigation behavior.
- Processing a new fragment directive will remove existing highlights
- Writing a new fragment will preserve/clone the current fragment directive (i.e. so navigating to `#foo` won't remove existing highlights, but navigating to `#foo:~:differentdirective` will)

I believe this also means that we'll no longer fire `hashchange` for changes in the fragment directive, since that happens as part by [comparing the URL on the history entries](https://html.spec.whatwg.org/multipage/browsing-the-web.html#update-document-for-history-step-application:~:text=%2C%20and%20oldURL%27s%20fragment%20is%20not%20equal%20to%20entry%27s%20URL%27s%20fragment).

> One thing to think about is what to do with failed matches. Eg:

This model wouldn't distinguish between failed/succeeded - the fragment directive is stored on an entry either way.

**Comment by jakearchibald** [comment]
> * Process the fragment directive when traversing history but don't cause scroll to the highlight. Scroll position will come from the saved scroll state (or avoided if scroll restoration is manual) - this matches regular fragment navigation behavior.
> * Processing a new fragment directive will remove existing highlights
> * Writing a new fragment will preserve/clone the current fragment directive (i.e. so navigating to `#foo` won't remove existing highlights, but navigating to `#foo:~:differentdirective` will)

One case to think about:

1. Navigate to `#:~:text=world` (page does not contain 'world')
2. Add 'world' to page.
3. Navigate to `#foo`.
4. `pushState({}, '', '/hello')`.

- Does 'world' highlight on step 3? Does it scroll to `#foo` or 'world'?
- Does it scroll to 'world' on step 4?

It feels like the scroll-to behaviour should only happen during the navigation where the directive is stripped from the URL.

Also, what's scrolled-to when navigating to `#foo:~:text=world`?

**Comment by jakearchibald** [comment]
https://jsbin.com/vohimek/3/quiet - here's another case that's different between Chrome & Safari.

**Comment by bokand** [comment]
In this example, is it the case it's all same-document because the entries mutate the URL via `pushState`?

Yes, I think you're right. I was assuming different (pre-fragment) URL would populate a new document which will reprocess the directive. WDYT of treating a changed pre-fragment URL the same as cross-document and processing the directive (and clearing it if the new URL didn't include a directive)?

I'm trying to avoid re-processing on fragment-only changes since

a) the text search is expensive
b) in the common case, page content didn't change
c) since the directive is preserved across fragment-only changes, it could cause weird behavior:
  * user navigates to `foo.html#:~:text=hello` - page doesn't contain "hello" 
  * page dynamically adds some text containing "hello"
  * user clicks a link to `foo.html#bar` - scrolls to bar but highlights hello

You might ask why we want to preserve the directive across fragment-only changes - this is intentional as we commonly came across pages that write to their fragment during loading, e.g.

* navigate to `foo.html` becomes `foo.html#`
* navigate to `bar.html` becomes `bar.html#page1`

We don't want this to clear/cancel highlighting. This does mean that history traversal on a page that uses the fragment for routing won't restore highlights but I think that's fine if it means the initial navigation can more reliably show the highlight.

**Comment by bokand** [comment]
To give an example of what I'm proposing:

| Navigate to | History Entry | Update Highlights |
| --------------- | -------------------| ------------------------------------|
|  `foo.html#:~:text=hello` | A: `foo.html` directive: `text=hello` | * |
| `foo.html#bar` | B: `foo.html#bar` directive: `text=hello` | |
| replaceState `bar.html` | B: `bar.html` directive: `text=hello` | |
| pushState `bar.html#bar` | C: `bar.html#bar` directive: `text=hello` | |
| pushState `new.html` | D: `new.html` directive: ` ` | * |
| pushState `new.html#:~:text=hello` | E: `new.html` directive: `text=hello` | * |

When traversing, we'll update highlights if:
- directive changed OR
- src and destination URLs differ after removing fragments

**Comment by bokand** [comment]
> The same "highlight state" can be reference by multiple history entries (eg, it's copied when navigating same-document).

Are you suggesting doing this for all same-document navigations? e.g. 

1. Navigate to `/page-1#:~:text=world` which contains "world" and is highlighted
2. Same-document navigate to `/page-2` which contains a different "world" but is not highlighted because its the same highlight state
3. Same-document navigate to `/page-3#:~:text=hello` which contains "hello" and is highlighted

Now if you:

* `back()` we'll highlight "world" on `page-2` though it wasn't the first time
* `back()` since the highlight state is the same we won't highlight the originally highlighted "world".

I think the highlight state is a better framing than comparing URLs, but perhaps we'd only re-use a state if only the (directive-stripped) fragment changed (which I think makes it behaviorally equivalent to my approach)? 

But also: does the spec have a notion of "references"? You say "it's copied when navigating same-document" but then you'd have two structs with the same data - presumably you mean that the history entry points to the previous entry's highlight state but can we do that in spec language? @annevk?

**Comment by jakearchibald** [comment]
> Are you suggesting doing this for all same-document navigations? e.g.

Yeah, what you describe sounds like what I was thinking.

> But also: does the spec have a notion of "references"? You say "it's copied when navigating same-document" but then you'd have two structs with the same data - presumably you mean that the history entry points to the previous entry's highlight state but can we do that in spec language?

Yeah, history entries also have a "document state" which can be shared by multiple history entries (entries that should use the same document).
