### ISSUE TITLE
Syntax for PercentEncodedChar looks wrong

### ISSUE THREAD

**Issue by hsivonen** [WICG/scroll-to-text-fragment#229]
https://wicg.github.io/scroll-to-text-fragment/#percentencodedchar says:

> PercentEncodedChar ::=
>    "%" [a-zA-Z0-9]+ 

That is, one or more hex digits.

https://url.spec.whatwg.org/#percent-encoded-bytes says:

> A percent-encoded byte is U+0025 (%), followed by two [ASCII hex digits](https://infra.spec.whatwg.org/#ascii-hex-digit).

It seems to me that the production should be:

> PercentEncodedChar ::=
>    "%" [a-zA-Z0-9][a-zA-Z0-9]

Aside: The name PercentEncodedChar is misleading, since what's being percent-encoded is a _byte_ rather than a character.

**Comment by hsivonen** [comment]
[It appears](https://encoding.spec.whatwg.org/#:~:text=U+FFFD%20(%F)&text=followed%20by%20the%20shortest%20sequence) that Chrome allows one hex digit (per the spec) in the validation step. ☹️

**Comment by bokand** [comment]
Thanks for the catch! Will fix the production.

> [It appears](https://encoding.spec.whatwg.org/#:~:text=U+FFFD%20(%F)&text=followed%20by%20the%20shortest%20sequence) that Chrome allows one hex digit (per the spec) in the validation step. ☹️

Chrome treats the two `text=` directives as independent of each other so if the first one were to fail as invalid, the second is still applied. This doesn't match the [spec text](https://wicg.github.io/scroll-to-text-fragment/#invoke-text-directives) which implies that the entire list should be discarded. Personally, I prefer Chrome's behavior of keeping directives independent so would like to change the spec text but am curious what you think.

Interestingly, Chrome does fail to decode the `%F` but this causes it to leave a `%` char in the matching string (i.e. this would match page text "U+FFFD (%F)"). This is a Chrome bug, I've filed https://crbug.com/1482847 (note: Safari behaves the same way)

**Comment by bokand** [comment]
I've updated the spec to fix the percent-encoding production. I'll add some WPTs for the cases mentioned above.
